### ISSUE TITLE
simulation test

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#138]
https://github.com/cosmos/gaia/blob/main/app/sim_test.go

https://github.com/cosmos/cosmos-sdk/tree/master/x/bank/simulation

**Comment by YasunoriMATSUOKA** [comment]
以下情報を確認の上、参考リンクの内容を確認して、実装の意図を理解して、優先度高の内容から実装をお願いしたいと思っています。

既存の単体テストとは異なり、結合テスト的な内容になります。

参考にすべきkavaのバージョン ... 後で追記します。注意点として、参考にすべきkavaのバージョンの時点では、Cosmos SDKのバージョンが古いv0.39.x系列だったこと。

実装する必要があるファイル、モジュール ... 記載している見積時間は特にトラブルなくスムーズに実装できた場合を木村さんにて想定してもらった時間を仮で記載しています。

- [ ] UnUniFi独自モジュール以外のところ
  - [ ] 優先度高
    - [ ] 参考 https://github.com/cosmos/gaia/blob/main/app/app.go#L521 ... 1～2時間
    - [ ] 参考 https://github.com/cosmos/gaia/blob/main/app/sim_test.go ... 2時間
- [ ] UnUniFi独自モジュール ... 実装方法の参考 https://github.com/cosmos/cosmos-sdk/tree/master/x/bank/simulation
  - [ ] 優先度高
    - [ ] auction ... 2日 ... 
    - [ ] cdp ... 3日
  - [ ] 優先度中
    - [ ] incentive ... 2日
    - [ ] ununifidist ... 2日
  -  仕様変更予定なので一旦保留
    -  pricefeed

スケジュール的には、メインネットローンチ(5月上旬想定)前には全機能網羅したいというイメージです。

**Comment by mkXultra** [comment]
@KimuraYu45z 
チェックボックスがありますが、進捗の状況もわかったりしますか？

**Comment by YasunoriMATSUOKA** [comment]
@mkXultra 
申し訳ないですが、正確に把握できていない感じです

**Comment by mkXultra** [comment]
@mkXultra 
承知しました
一旦現状の把握から進めていきたいと思います

**Comment by mkXultra** [comment]
#156

**Comment by mkXultra** [comment]
独自モジュールのテストはcosmos v42系を参考にしているためv45(main branche)に変更する

**Comment by mkXultra** [comment]
kavaのmain branchがかなり参考になるので、そっちを参照しながら進めていく

**Comment by mkXultra** [comment]
独自モジュールテストは以下のIFを定義し、それをsimulation managerが内部的にコールする気がする
https://github.com/cosmos/cosmos-sdk/blob/be4a965599dfae6992451e4b5135c487ed45053b/types/module/simulation.go#L16-L31

**Comment by mkXultra** [comment]
@KimuraYu45z @YasunoriMATSUOKA 
モジュールテスト用の関数のテストは実装しますか？
kavaでは一部のみしか実装されていませんが、cosmos-sdkでは実装されています
https://github.com/Kava-Labs/kava/tree/master/x/kavadist/simulation
https://github.com/cosmos/cosmos-sdk/tree/master/x/bank/simulation

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z 
以下リンクの質問の件、申し訳ないですが @YasunoriMATSUOKA にて正確に意図を理解できていない気がしていて、フォロー頂けないでしょうか？お手数ですがよろしくお願いしますm(__)m
https://github.com/UnUniFi/chain/issues/138#issuecomment-1073432587

**Comment by KimuraYu45z** [comment]
@YasunoriMATSUOKA 
kavaは

- https://github.com/Kava-Labs/kava/blob/master/x/kavadist/simulation/decoder_test.go
 
しか実装してないが、
cosmos sdkでは

- https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/simulation/genesis_test.go
- https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/simulation/operations_test.go
- https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/simulation/params_test.go

これらすべて実装されているという意味ですね。

@mkXultra 

最終的には必要な気がするので、実装することにしましょう。ただし工数膨れそうだったらまた別途相談お願いします。
cdpなど重要モジュールでは膨れそうです。一方でununifidistなんかはkavadistくらいでいいとも思います。

**Comment by mkXultra** [comment]
@KimuraYu45z @YasunoriMATSUOKA 
Kavaのシュミレーションテストはメンテされていないかつ、動作させていないので予定した工数よりも膨らむ可能性があります（どこまでコードを再利用できるかわかりません

**Comment by mkXultra** [comment]
@mkXultra 
テスト
