### ISSUE TITLE
cosmwasm module

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#143]
https://github.com/CosmWasm/wasmd/blob/master/app/app.go

**Comment by YasunoriMATSUOKA** [comment]
Status

- [x] Implementation
- [x] Go build
- [ ] Docker image build with GitHub Actions CD ... https://github.com/UnUniFi/chain/issues/154

**Comment by YasunoriMATSUOKA** [comment]
Low priority
