### ISSUE TITLE
Forgot private key

### ISSUE THREAD

**Issue by Jigs12332** [UnUniFi/chain#144]
Hi dear sir/medam
I have faced same issue 
When i fill this airdrop  nd create new account 
I totally forgot to recover private key 
Now when i see airdrop winner list 
My acc address show in winners list
But when i go in website it's show enter your private key nd that i dont have so please help me dear sir/medam
I humble request you

**Comment by YasunoriMATSUOKA** [comment]
@Jigs12332 

Thank you for creating the Issue.

Did you back up your mnemonic phrase as a text file when you performed the AirDrop task?

If you did, you can use the mnemonic phrase to restore your account at the following link
http://a.test.ununifi.cauchye.net/keys/create
Enter your mnemonic phrase in the Mnemonic field and remove focus from the Mnemonic field **without clicking the create button**, and your private key will be automatically calculated and entered. Then, you can click Submit to restore your account.

If you did not back up your account, it is technically impossible to restore it, so please create a new account and perform the AirDrop task again with that account.

**Comment by YasunoriMATSUOKA** [comment]
No response, so I will close it.
If you have any questions again, please contact us again.
