### ISSUE TITLE
CD to build and push new docker image to ghcr.io fail

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/chain#154]
**Describe the bug**

After merging https://github.com/UnUniFi/chain/pull/151, CD to push docker image to ghcr.io fails.
https://github.com/UnUniFi/chain/actions/runs/1816402836

**To Reproduce**

nothing

**Expected behavior**

CD should be success and push new docker image to ghcr.io with test tag.

**Screenshots**

nothing

**Desktop (please complete the following information):**

nothing

**Smartphone (please complete the following information):**

nothing

**Additional context**

Following PR is not contained in UnUniFi Nod's docker image with test tag.

https://github.com/UnUniFi/chain/pull/151
https://github.com/UnUniFi/chain/pull/152

**Comment by mkXultra** [comment]
着手します

**Comment by mkXultra** [comment]
@YasunoriMATSUOKA 
#155 
終わったので、レビューお願いします

**Comment by YasunoriMATSUOKA** [comment]
@mkXultra 
解決ありがとうございました。
クローズしておきます。
