### ISSUE TITLE
【ununifi-8-private-test】Faucet exceeds Limit per account

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/chain#161]
When getting a balance in Faucet, the maximum value may be exceeded. In this case, an error message will still be displayed, but the balance will be granted.
![スクリーンショット 2022-03-04 152132](https://user-images.githubusercontent.com/29295263/156710897-15637c48-1f0b-42eb-ae15-8c695c924131.png)

**Comment by YasunoriMATSUOKA** [comment]
Move to appropriate repository
