### ISSUE TITLE
Some files seem to be unnecessary

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/chain#200]
**Describe the bug**

This is not a bug but some files are unnecessary?
They are only for debug or communication?
They should be removed?
(Of course priority can be low.)

- [ ] https://github.com/UnUniFi/chain/blob/develop/start.sh ... Sorry, this was my commit. This file is only for debug. I guess this can be removed.
- [ ] https://github.com/UnUniFi/chain/tree/develop/txs ... I think this directory is for information sharing purposes to clarify transaction type recognition between the front end and back end. I guess this can be removed but I'm not sure.
  - [ ] https://github.com/UnUniFi/chain/blob/develop/txs/bank-send.json
  - [ ] https://github.com/UnUniFi/chain/blob/develop/txs/sign-bytes.json

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by taikiFurusyo** [comment]
this issue #188 , too.
