### ISSUE TITLE
Hooks in x/nftmarket and Method to get memo to pass in the hook

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/chain#218]
For the `frontend-incentive` module, I'd like x/nftmarket module to have hooks for the timing of listing NFT and ending listing.

The hook style reference is here:
https://github.com/UnUniFi/chain/blob/main/x/cdp/types/hooks.go
https://github.com/UnUniFi/chain/blob/main/x/cdp/keeper/hooks.go

This hook style doesn't create the two-way interaction between the modules using the hooks.

And, in the listing creation hook, a memo data is required to be in.

**Comment by taiki1frsy** [comment]
The Nftmarket hooks interface:

```
type NftmarketHooksk interface {
   AfterNftListed(ctx sdk.Context, nft_id types.NftIdentifier)
   AfterNftPaid(ctx sdk.Context, fee_amount mathInt, fee_denom string)
}
```

**Comment by taiki1frsy** [comment]
The reference to get memo data in a specific tx that contrains specific message:
https://github.com/UnUniFi/chain/blob/how_to_get_memo/x/nftmint/keeper/get_memo.go
https://github.com/UnUniFi/chain/blob/7ff59554a534bf4e63d8a5b330404c67e1f94b69/x/nftmint/keeper/msg_server.go#L37

**Comment by taiki1frsy** [comment]
I'll work on this for `ecosystem-incentive` module, but this has to be done in `nftmarket` module.
So I'll make a change on newDevelep on the other branch than the fundamental part of the `ecosystem-incentive` module.
