### ISSUE TITLE
proto config and the way to generate files from them

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/chain#224]
Currently, we place third party proto files directly in our repository without having buf configs under proto folder to configure the rules to generate files from proto files.
Also we use old versin of buf and protoc to be compatible with the old way to generate them.
So the goal is to remove `buf protoc` way and construct new way to generate go files from proto files with `buf generate` command.
References:
https://github.com/osmosis-labs/osmosis/blob/ab06a4f8e938f930c4cc9bab5606f453a88c9ac6/Makefile#L168
https://github.com/osmosis-labs/osmosis/blob/ab06a4f8e938f930c4cc9bab5606f453a88c9ac6/scripts/protocgen.sh
https://github.com/osmosis-labs/osmosis/blob/ab06a4f8e938f930c4cc9bab5606f453a88c9ac6/scripts/generate-proto.sh

**Comment by taiki1frsy** [comment]
When this issue will be addresses, please do these below issues at the same time.
https://github.com/cosmos-client/cosmwasm-ts/issues/4
https://github.com/cosmos-client/ununifi-ts/issues/14

They're related issues and require drastic point for both of them.
So, after solving those issues all, submit PRs for each repo.

**Comment by hikaruNagamine** [comment]
https://github.com/cosmos-client/cosmwasm-ts/pull/10
https://github.com/cosmos-client/ununifi-ts/pull/19

**Comment by hikaruNagamine** [comment]
@taiki1frsh 
I changed to use the buf generate command and addressed the issue of third-party proto files not being in the repository and not being referenced.
We would appreciate your confirmation that you are aware of the perspective of the fixes.🙇‍♂️

**Comment by taiki1frsh** [comment]
@hikaruNagamine 
yes, i'm aware of those.
- we should use latest version of buf tools 
- we shouldn't have third-party proto files in the repository directory

these two are the stuff to be achieved for this issue, I think.
