### ISSUE TITLE
proto camelcase NFT

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/chain#230]
https://github.com/UnUniFi/chain/tree/newDevelop/proto/nftmint

In newDevelop, `NFT` used in nft-mint proto. But, I reccomend `Nft` like `Cdp`, `Id`, `Uri` , etc.
After change them, we will change `ununifi-ts` & Bubble Plugin.

**Comment by KimuraYu45z** [comment]
http://blog.codic.jp/2014/11/13/about-camel-case/

two-character words are sometimes kept as capital letters

**Comment by Senna46** [comment]
Now, both `NFT` and `Nft` are used by Msg. This is very confused, Nft is more often used in some Msg and also easier to read, so I would like it to match this one.

**Comment by KimuraYu45z** [comment]
I think it is better to unify `NFT`
