### ISSUE TITLE
organize branches

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#305]
We need to organize branches.
There are too many branches.

**Comment by KimuraYu45z** [comment]
- `feat/issue309` description here
- `feat/issue302`
- `upgrade/upgrade_v2`
- `feat/issue307`
- `newDevelop`
- `feature/e2e_setup`
- `feat/derivatives`
- `feature/nftmarket_v2_impl`
- `ibc_staking_code`
- `design/nftmarket_v2`
- `impl-intertx-ibc-go-v3`
- `impl-intertx`
- `for_ibc_test`
- `feature/decentralized_vault`
- `aggregator_on_wasm_branch`
- `feature/late_shipping_nft`

**Comment by KimuraYu45z** [comment]
Stale branches

- `feature/add-simulation-test` @mkXultra 
- `feature/error_genesis_json` @mkXultra 
- `upgrade/twice_upgrade_test` @mkXultra 
- `upgrade/add_pricefeed_param` @mkXultra 
- `feature/listing_and_nft_mint2` @mkXultra 
- `feature/listing_and_nft_mint` @mkXultra 
- `develop`
- `nftmarket_historical_information` @jununifi 
- `tmp/stable_nftmarket_implementation` @mkXultra 
- `simapp-based-test-setup` @taiki1frsh 
- `feature/support_v046_rc1` @mkXultra 
- `how_to_get_msg_events` @taiki1frsh 
- `how_to_get_memo` @taiki1frsh 
- `spec-nftmarket-incentive` @taiki1frsh 
- `tests/nftmint-queries` @taiki1frsh 
- `upgrade/enable_q3_module` @mkXultra 
- `feature/yield_aggregator` @jununifi

**Comment by KimuraYu45z** [comment]
@mkXultra @taiki1frsh @jununifi please note which branch is for `cosmos-sdk v0.45.x`, which branch is for `cosmos-sdk v0.46.x`, which branch is for cosmwasm

**Comment by mkXultra** [comment]
@KimuraYu45z 
I did it.

**Comment by KimuraYu45z** [comment]
thanks
