### ISSUE TITLE
Add JSON to response QueryIncentiveUnit

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/chain#306]
`/ununifi/ecosystem_incentive/incentive_unit/{incentive_unit_id}`
return 
https://github.com/UnUniFi/chain/blob/c35e4a84d36b387704e820fc297861ed304b8737/proto/ecosystem-incentive/ecosystem_incentive.proto#L9

The JSON string that should be included in the memo is not included in this response. 
We shoud add the func to `rpc IncentiveUnit`

**Comment by taiki1frsh** [comment]
@Senna46 
is this quickly needed?

**Comment by Senna46** [comment]
Yes, need before the release of the ecosystem-incentive along with #302, I think

**Comment by taiki1frsh** [comment]
do this somewhere except for backend side
