### ISSUE TITLE
[derivatives] Pair price rate method to be modified

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/chain#379]
Get pair rate by dividing `base_denom` by `quote_denom` price in the backend and return it as pair rate.

**Comment by mkXultra** [comment]
@taiki1frsh 
I was deleted PairPrice method.
Can I close this isseu?

**Comment by taiki1frsh** [comment]
@mkXultra 
can you give me more information about that?

**Comment by mkXultra** [comment]
@taiki1frsh 
Sorry, I misunderstood.
Why is it necessary?
