### ISSUE TITLE
new branch operation

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#436]
Before CosmWasm supports SDK v0.46

- main
  - correspond to mainnet
- develop
  - nft-backed-loan
  - derivatives
- develop045
  - yield-aggregator
  - cosmwasm 

After CosmWasm supports SDK v0.46 or v0.47, merge everything.

**Comment by KimuraYu45z** [comment]
After CosmWasm supports SDK v0.46 or v0.47, merge everything, and then

- develop
  - correspond to alpha testnet
- main
  - correspond to beta testnet and demo net
- tag and release
  - correspond to mainnet and normal testnet

**Comment by mkXultra** [comment]
https://cauchye.slack.com/archives/C03FYL68J20/p1679020535246819
