### ISSUE TITLE
[derivatives] Handle the different of the unit scale between position size and margin asset

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/chain#447]
When calculating the margin requirement, the Position size unit scale must be modified to the scale of the margin asset.

The solution could be:
- Simply multiply one million every time when calculating the margin requirement
- Make PositionInstance have denom information to be multiplied when calculating the margin requirement and use it to multiply
- Change position instance scale from the default 
- Make it micro level every time `Position Size` is used on the backend
...

I think the middle of the above candidates would be desirable.
What do you think?
@mkXultra @KimuraYu45z

**Comment by taiki1frsh** [comment]
This issue has to be fixed with this issue #447. 
These unit confusions are originally caused by #447 partially.

**Comment by KimuraYu45z** [comment]
Reference:
https://github.com/UnUniFi/chain/issues/469
If you want to make position size based in micro unit, plz make Size_ field as `sdk.Int`

**Comment by taiki1frsh** [comment]
@KimuraYu45z 
I tried to add a new field called "SizeInMicro" and use it in the backend logic while I don't touch the interfaces like query resopnce etc
