### ISSUE TITLE
[derivatives] Total position size in metrics quote ticker isn't handled appropriately

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/chain#448]
There are some positions, but the Total is 0 USD.
http://ununifi-beta-test.cauchye.net:1317/ununifi/derivatives/perpetual-futures
```
{
  "metrics_quote_ticker": "USD",
  "volume_24hours": "0.000000000000000000",
  "fees_24hours": "0.000000000000000000",
  "long_positions": {
    "denom": "uusd",
    "amount": "0"
  },
  "short_positions": {
    "denom": "uusd",
    "amount": "0"
  }
}
```
http://ununifi-beta-test.cauchye.net:1317/ununifi/derivatives/positions

**Comment by mkXultra** [comment]
https://github.com/UnUniFi/lab-test/issues/77

**Comment by taiki1frsh** [comment]
@Senna46 @mkXultra cc: @KimuraYu45z 

I found out the cause of this issue.
But, it cannot be solved in no time.

In short, the current implementation doesn't handle `PerpetualFuturesNetPositionOfMarket`correctly to reflect the total position size on the perpetual futures.
The code adds position size when long is taken and "deducts" position size when short is taken.
The latter part is the cause of the reason.

**Comment by taiki1frsh** [comment]
#481
