### ISSUE TITLE
[derivatives] create counter position when a position is created by a trader

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/chain#451]
This may be able to be achieved by allocating corresponding pool assets for each position (more technically, ***Lock that corresponding asset***).

This is needed by the protocol design itself.
But, nowhere I can see the implementation of this at this moment.

**Comment by KimuraYu45z** [comment]
1. If pool can't pay reward to the trader, rewards will not paid
2. If trader got losses over margin, pool will give it up.

For 1., FE side must show the alert when pool might not be able to pay reward
