### ISSUE TITLE
[derivatives] position size precision

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#469]
Imagine ATOM/BTC market and taking 2.5ATOM Long position.

Position size is 2.5.

Then, we have to input 2.5 in `PositionInstance.Size_`.
We must not input `2500000` in  `PositionInstance.Size_` like `uatom` or something like that.

**Comment by Senna46** [comment]
#447

**Comment by taiki1frsh** [comment]
As @Senna46 suggests, #447 is already there for this and I'm trying to fix at https://github.com/UnUniFi/chain/pull/467
