### ISSUE TITLE
[Derivatives] OpenPosition The second and subsequent times Tx fail

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/chain#483]
On Alpha test.
1. Put enough balance in Pool after network reset
2. Send OpenPosition => success
3. Send OpenPosition again, this tx always fails.
`"timed out waiting for tx to be included in a block"`

I have tried to redo it many times and it is the same.
After this occurs, nobody can send tx. 

There is a problem with OpenPosition Tx processing, I think.

**Comment by Senna46** [comment]
![positions](https://user-images.githubusercontent.com/29295263/231073716-9afc2c71-ca33-4cba-902b-fe0bccbdb6be.gif)
After that, other user's any Txs (Delegate, Send) are same error.`timed out waiting for tx to be included in a bloc`
this user's tx are mismatch in account sequence.

**Comment by taiki1frsh** [comment]
Does the first tx really succeed?
can you confirm that?

**Comment by Senna46** [comment]
As shown in the gif, a Position has also been created.

**Comment by taiki1frsh** [comment]
In local, creating position after the creation of the position succeeds.

Alpha node seems dead after the creation of the position.
But, don't know the cause since it succeeds in local.
continue to investigate

**Comment by Senna46** [comment]
For your reference
```
"position": {
        "id": "1",
        "market": {
          "base_denom": "ubtc",
          "quote_denom": "uusdc"
        },
        "address": "ununifi155u042u8wk3al32h3vzxu989jj76k4zcu44v6w",
        "opened_at": "2023-04-11T06:19:45.862155664Z",
        "opened_height": "17",
        "opened_base_rate": "0.024508410211260500",
        "opened_quote_rate": "0.000001001479651825",
        "remaining_margin": {
          "denom": "ubtc",
          "amount": "-249500000"
        },
        "last_levied_at": "2023-04-11T06:19:50.877513680Z",
        "position_instance": {
          "@type": "/ununifi.derivatives.PerpetualFuturesPositionInstance",
          "position_type": "LONG",
          "size": "1.000000000000000000",
          "leverage": 2
        }
      },
      "valuation_profit": {
        "denom": "uusd",
        "amount": "0"
      },
      "remaining_margin_value": "0.000000000000000000",
      "effective_margin": {
        "denom": "uusd",
        "amount": "-6114848"
      },
      "margin_maintenance_rate": "-499.008323812632609760"
    }
```
http://ununifi-alpha-test.cauchye.net:1317/ununifi/derivatives/positions

Msg
![スクリーンショット 2023-04-11 155512](https://user-images.githubusercontent.com/29295263/231081185-2f913d70-c212-4172-b21a-0e13a59f9cda.png)

![スクリーンショット 2023-04-11 155749](https://user-images.githubusercontent.com/29295263/231081245-7370fe03-3ad6-4edb-8b3b-d3dc5792a6c1.png)

**Comment by taiki1frsh** [comment]
hmm, obviously margin value is invalid.
let me see it

**Comment by Senna46** [comment]
OK.

**Comment by taiki1frsh** [comment]
Re-created issue for this bug at #485
