### ISSUE TITLE
Ecosystem Incentive Query return error

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/chain#501]
If the address has no unit, the Query IncentiveUnitIdsByAddr return error.
It should return an empty array [].
http://ununifi-alpha-test.cauchye.net:1317/ununifi/ecosystem_incentive/incentive_unit_ids_by_addr/ununifi155u042u8wk3al32h3vzxu989jj76k4zcu44v6w
```
{
  "code": 2,
  "message": "codespace ecosystemincentive code 15: the address deosn't have any incentive unit id",
  "details": [
  ]
}
```

**Comment by Senna46** [comment]
RewardQuery has same problem.

@taiki1frsh please do so after completing the task you are currently holding.

**Comment by taiki1frsh** [comment]
Got it
