### ISSUE TITLE
band protocolの組み込み方法調査

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#7]
https://twitter.com/CosmosNetworkJP/status/1413514194570207236

**Comment by YasunoriMATSUOKA** [comment]
@mkXultra cc: @KimuraYu45z 

Reference

- Blockchain: https://github.com/bandprotocol/bandchain
- Docs: https://docs.bandchain.org/
- SDK for Frontend?: https://github.com/bandprotocol/bandchain.js ... Refer to the API usage examples.
- Reference Implementation to get oracle data through IBC?: https://github.com/bandprotocol/chain
- Another reference: https://docs.bandchain.org/whitepaper/cosmos-ibc.html

Tasks

- [ ] Investigate the way to call REST API of gRPC of band protocol.
- [ ] "Find a list of nodes that can use REST API or gRPC." or "Create a node." ... If you need to set up a node, we may be able to prepare the infrastructure. (Maybe we have some servers that was originally reserved for another project. (ex. EURX))
- [ ] Implementation ... The following 3 patterns can be assumed. When I discussed this with Mr. Kimura before, we came to the conclusion that method 3 would be preferable.

1. In Node.js pricefeed program, call band protocol api and postPrices and use it. ... This is the simplest, but we are concerned about the need for our own oracle-like scripts to run properly separately from the nodes, and for each node owner to maintain them properly, and we want to keep this to a minimum if possible. We are also concerned about the ongoing fees.
2. In Go, send IBC Tx to get oracle data from band chain through IBC and use it. ... There is still a concern that fees will continue to be charged.
3. In Go, call band protocol's REST API or gRPC directly and use it. ... In this way, there is no need of fees?

**Comment by mkXultra** [comment]
kava use "Chainlink"
https://github.com/Kava-Labs/kava/blob/de750103ca605c2e9d28821e846b4089716a1942/docs/kava-8/upgrade_oracle.md

**Comment by mkXultra** [comment]
Use oracle when creating cdp 
https://blog.cosmos.network/guide-to-building-defi-using-band-protocol-oracle-and-cosmos-ibc-fa5348832f84

**Comment by mkXultra** [comment]
bandchain.js is broken
error message: Error: This feature can be taken from extra/rest branch
issue: https://github.com/bandprotocol/bandchain.js/issues/32

**Comment by mkXultra** [comment]
REST API is working
https://laozi1.bandchain.org/api//oracle/v1/request_prices?symbols=JPY

**Comment by mkXultra** [comment]
How to create a public node:
https://medium.com/bandprotocol/bandchain-wenchang-stage-3-begins-with-public-node-12e31ff2c0e

**Comment by mkXultra** [comment]
A repository where genesis.json of bandchain is placed
https://github.com/bandprotocol/launch

**Comment by mkXultra** [comment]
laozi main net
https://github.com/bandprotocol/launch/tree/master/laozi-mainnet

**Comment by mkXultra** [comment]
lanch script
```
#testnet
export CHAIN_ID=band-laozi-testnet4;
export WALLET_NAME=my_validator;
export MONIKER=band_test1;
export SEEDS=9934156cd42fc708b10232746c3e68c1bb999e86@34.87.49.160:26656,e847ebab344857475e8184943e7a40b80a6dda8e@34.85.134.225:26656;
export GENESIS_FILE_URL=https://raw.githubusercontent.com/bandprotocol/launch/master/band-laozi-testnet4/genesis.json;
export BIN_FILES_URL=https://raw.githubusercontent.com/bandprotocol/launch/master/band-laozi-testnet4/files.tar.gz;
export FAUCET_URL=https://laozi-testnet4.bandchain.org/faucet;

rm -rf ~/.band;
bandd init --chain-id $CHAIN_ID "$MONIKER";
wget $GENESIS_FILE_URL -O $HOME/.band/config/genesis.json;
wget -qO- $BIN_FILES_URL | tar xvz -C $HOME/.band/;
bandd keys add $WALLET_NAME --recover --keyring-backend test < bnd_mnt.txt;
sed -E -i "s/seeds = \".*\"/seeds = \"$SEEDS\"/" $HOME/.band/config/config.toml;
mkdir ~/.band/data/files;
mkdir ~/.band/files;
sudo chmod  777 ~/.band -R;
bandd start


#mainnet
export CHAIN_ID=laozi-mainnet;
export WALLET_NAME=my_validator;
export MONIKER=band_test1;
export SEEDS=8d42bdcb6cced03e0b67fa3957e4e9c8fd89015a@34.87.86.195:26656,543e0cab9c3016a0e99775443a17bcf163038912@34.150.156.78:26656;
export PEERS=98823087b61d442a4ab86998709c77b2e517ee78@35.240.152.216:26656,3ea84babead3d6bc488810a0f2cf0744cf5c68fe@34.86.22.251:26656,48f26a2c8d238b01124d49818c3bddba826c4356@136.243.5.247:58856,d047cfabdfd5e244af530d6d2101d07c45ff7424@165.22.167.234:41656,1a4af7cbd3db94a3881dc35cfa261ec2ac788f8f@91.246.64.247:26656,c1b93580023f12891683431e25fb05d6e4372bef@188.34.207.243:26656,2f62588be3cf41a019289097c2068c4e65aa5e37@95.217.213.135:26656,58ce8a2bd441057c0b18d0812f692b2d8af55af7@168.119.61.205:26656,570787c6484fb5aef9182f032dbd54042d93b93c@35.82.85.220:26656,cb777d12ec515884f9f8153e2bbe1844079323a4@44.234.200.116:26656,cacb630ef586ffefccf103d442c02bdbc187f996@3.37.82.201:26656,39d45dae55f36db42ef3997376efbbf725666f75@51.38.53.4:30656,70c542ec2e1aebb385f7e93d1c55f1a4073cdcb7@54.38.46.124:30656,d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb@51.91.67.48:30656,96b1e7c754ef5a8f80be569a30de21f9675589c9@13.232.162.252:26656
export GENESIS_FILE_URL=https://raw.githubusercontent.com/bandprotocol/launch/master/laozi-mainnet/genesis.json;
export BIN_FILES_URL=https://raw.githubusercontent.com/bandprotocol/launch/master/laozi-mainnet/files.tar.gz;
export FAUCET_URL=https://laozi-testnet4.bandchain.org/faucet;


rm -rf ~/.band;
bandd init --chain-id $CHAIN_ID "$MONIKER";
wget $GENESIS_FILE_URL -O $HOME/.band/config/genesis.json;
bandd keys add $WALLET_NAME --recover --keyring-backend test < bnd_mnt.txt;
sed -E -i "s/seeds = \".*\"/seeds = \"$SEEDS\"/" $HOME/.band/config/config.toml;
sed -E -i "s/persistent_peers = \".*\"/persistent_peers = \"$PEERS\"/" $HOME/.band/config/config.toml;
mkdir ~/.band/data/files;
mkdir ~/.band/files;
sudo chmod  777 ~/.band -R;
bandd start;

```

**Comment by mkXultra** [comment]
bandのlocal APIサーバにgetpriceする方法
```
//go 1.6 install
git clone --depth 1 --branch extra/rest https://github.com/bandprotocol/chain
cd chain
make install

//just once
bandd keys mnemonic > mnt_band.txt

//setup band
bandd init --chain-id $CHAIN_ID "$MONIKER";
sed -E -i "s/seeds = \".*\"/seeds = \"$SEEDS\"/" $HOME/.band/config/config.toml;
sed -i '/\[api\]/,+3 s/enable = false/enable = true/' ~/.band/config/app.toml;
wget $GENESIS_FILE_URL -O $HOME/.band/config/genesis.json;
bandd keys add $WALLET_NAME --recover --keyring-backend test < mnt_band.txt;

//sync file setup
//need 250GB disk space
cd $HOME/.band
URL=`curl https://quicksync.io/band.json|jq -r '.[] |select(.file=="laozi-mainnet-pruned")|.url'`
wget -O - $URL | lz4 -d | tar -xvf -
cd $HOME/.band/config
wget https://quicksync.io/addrbook.band.json

//sync mainnet
bandd start --with-pricer "3,4"

//another shell
curl -X GET "localhost:1317/oracle/v1/request_prices?symbols=JPY&symbols=EUR&ask_count=16&min_count=10"

```

**Comment by mkXultra** [comment]
@KimuraYu45z @YasunoriMATSUOKA 
予定していた調査は終了した認識です
しかしREST_APIから価格データを取得する場合は、masterブランチからではなくextra/restからビルドしてスタート時にフラグを付けないといけません
なぜこの仕様になったのか調査せずに実装検討していくのは危険だと思います
なので、一旦なぜbandはわざわざブランチ切ってまでAPIを使えなくしたか調べる必要があると思いますがどうでしょうか？

**Comment by KimuraYu45z** [comment]
> 一旦なぜbandはわざわざブランチ切ってまでAPIを使えなくしたか調べる必要がある

おっしゃる通りだと思います。

実装方針も違和感ありません。言語はgoで統一しておきますか？

**Comment by mkXultra** [comment]
@KimuraYu45z 
データプロバイダーが何かで壊れた時にununifiのバリデータがデータプロバイダーを切り替えれるようにした方が良いと思いました
その場合config(yaml?json?)を読んでプロバイダーを切り替えるようにした方がよいと思います
上記観点でいくと少し実装にボリュームが出ると思います
GOだと私の実装スピードは少し落ちます
Node.jsの方が実装は早いです
個人的にはGOで書きたいのですが、速度観はどんな感じでしょうか？

**Comment by KimuraYu45z** [comment]
goで書きたいということであればgoで大丈夫です！

データプロバイダーのバックアップ体制ちょっと考えます。

**Comment by mkXultra** [comment]
https://github.com/Kava-Labs/kava-tools

**Comment by YasunoriMATSUOKA** [comment]
@mkXultra cc: @KimuraYu45z 
2, 3は、UnUniFiのノードとは別サーバー別マシンで、band protocolのノードを立てて、我々で管理しつつ、band protocolのRest APIは我々の指定したネットワークからしか叩けないようにガードするといった形の方が色々やりやすいかもといったことを思いました。いったんデバッグする上では公開されているRest APIがあれば、それを使う形でもOKだと思います。

**Comment by mkXultra** [comment]
Docker環境作成はそこまで作業コスト高くないので、やっちゃいますね！

**Comment by mkXultra** [comment]
@mkXultra 
test
